---
- name: Install and configure Apache Web Server
  hosts: servers
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: |
          Apache deployed using Jenkins + Ansible
          Node: node4
        dest: /var/www/html/index.html


